### ISSUE TITLE
Unrecongized font family "FontAwesome"

### ISSUE THREAD

**Issue by ryuaus26** [Mazahir26/Reminder-App#28]
When I run the app I get the following error: 
Unrecognized font family 'FontAwesome'

+[ABI40_0_0RCTFont updateFont:withFamily:size:weight:style:variant:scaleMultiplier:]
    ABI40_0_0RCTFont.mm:329
+[ABI40_0_0RCTFont(ABI40_0_0UMReactFontManager) ABI40_0_0UMUpdateFont:withFamily:size:weight:style:variant:scaleMultiplier:]
-[ABI40_0_0RCTTextAttributes effectiveFont]
-[ABI40_0_0RCTTextAttributes effectiveTextAttributes]
-[ABI40_0_0RCTBaseTextShadowView attributedTextWithBaseTextAttributes:]
-[ABI40_0_0RCTTextShadowView attributedTextWithMeasuredAttachmentsThatFitSize:]
-[ABI40_0_0RCTTextShadowView textStorageAndLayoutManagerThatFitsSize:exclusiveOwnership:]
ABI40_0_0RCTTextShadowViewMeasure
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodeComputeFlexBasisForChild(ABI40_0_0YGNode*, ABI40_0_0YGNode*, float, ABI40_0_0YGMeasureMode, float, float, float, ABI40_0_0YGMeasureMode, ABI40_0_0YGDirection, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodeComputeFlexBasisForChild(ABI40_0_0YGNode*, ABI40_0_0YGNode*, float, ABI40_0_0YGMeasureMode, float, float, float, ABI40_0_0YGMeasureMode, ABI40_0_0YGDirection, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodelayoutImpl(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int, ABI40_0_0facebook::yoga::LayoutPassReason)
ABI40_0_0YGLayoutNodeInternal(ABI40_0_0YGNode*, float, float, ABI40_0_0YGDirection, ABI40_0_0YGMeasureMode, ABI40_0_0YGMeasureMode, float, float, bool, ABI40_0_0facebook::yoga::LayoutPassReason, ABI40_0_0YGConfig*, ABI40_0_0facebook::yoga::LayoutData&, void*, unsigned int, unsigned int)
ABI40_0_0YGNodeCalculateLayoutWithContext
-[ABI40_0_0RCTShadowView layoutWithMinimumSize:maximumSize:layoutDirection:layoutContext:]
-[ABI40_0_0RCTRootShadowView layoutWithAffectedShadowViews:]
-[ABI40_0_0RCTUIManager uiBlockWithLayoutUpdateForRootView:]
-[ABI40_0_0RCTUIManager _layoutAndMount]
__41-[ABI40_0_0RCTCxxBridge batchDidComplete]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread

**Comment by Mazahir26** [comment]
I regret to inform you that this project is not maintained. Many of its dependencies are outdated, and significant code rewriting would be necessary for it to function correctly. Thank you for taking the time to view and open an issue.
